# This is a Docker Compose file to work with Loud ML and an InfluxDB stack.

version: "3.6"

services:
  loudml:
    image: loudml/loudml:latest-devel
    volumes:
      - ./data/loudml.yml:/etc/loudml/config.yml:ro
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf
    depends_on:
      - influxdb
      - loudml
      - kapacitor
    ports:
      - "8888:8888"
    volumes:
      - ./data/chronograf:/var/lib/chronograf
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
      KAPACITOR_URL: http://kapacitor:9092

  kapacitor:
    image: kapacitor
    depends_on:
      - influxdb
    volumes:
      - ./data/kapacitor:/var/lib/kapacitor
    environment:
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086


